# Generated by Django 5.1 on 2024-08-20 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattlefieldCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('winner', models.CharField(choices=[('Caldari', 'Caldari'), ('Gallente', 'Gallente'), ('Minmatar', 'Minmatar'), ('Amarr', 'Amarr')], max_length=10)),
                ('system', models.CharField(max_length=100)),
            ],
        ),
    ]
