# Generated by Django 5.1 on 2024-08-22 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 1, 40, 57, 382625, tzinfo=datetime.timezone.utc)),
        ),
    ]
