# Generated by Django 5.1 on 2024-08-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='am_system',
            name='base_advantage',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cg_system',
            name='base_advantage',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
