# Generated by Django 5.1 on 2024-08-24 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbattlefield',
            name='default_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=models.DateField(default=django.utils.timezone.now)),
        ),
    ]
