# Generated by Django 5.1 on 2024-08-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0002_am_system_base_advantage_cg_system_base_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldcompletion',
            name='fc',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livebattlefield',
            name='fc',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
