# Generated by Django 5.1 on 2024-08-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0002_alter_scheduledbattlefield_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 17, 9, 54, 793682, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
