# Generated by Django 5.1 on 2024-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0002_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldcompletion',
            name='owner',
            field=models.CharField(choices=[('Caldari', 'Caldari'), ('Gallente', 'Gallente'), ('Minmatar', 'Minmatar'), ('Amarr', 'Amarr')], default='Caldari', max_length=10),
            preserve_default=False,
        ),
    ]
