# Generated by Django 5.1 on 2024-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0003_battlefieldcompletion_fc_alter_livebattlefield_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='am_system',
            name='base_advantage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cg_system',
            name='base_advantage',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
