# Generated by Django 5.1 on 2024-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0003_battlefieldcompletion_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
