# Generated by Django 5.1 on 2024-08-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0003_alter_scheduledbattlefield_expected_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livebattlefield',
            name='fc',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 18, 59, 23, 165986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
