# Generated by Django 5.1 on 2024-08-22 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0004_alter_scanresult_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBattlefield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('defender', models.CharField(choices=[('Caldari', 'Caldari'), ('Gallente', 'Gallente'), ('Minmatar', 'Minmatar'), ('Amarr', 'Amarr')], max_length=10)),
                ('fc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledBattlefield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('defender', models.CharField(choices=[('Caldari', 'Caldari'), ('Gallente', 'Gallente'), ('Minmatar', 'Minmatar'), ('Amarr', 'Amarr')], max_length=10)),
                ('fc', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='battlefieldcompletion',
            old_name='time',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='battlefieldcompletion',
            old_name='owner',
            new_name='defender',
        ),
    ]
