# Generated by Django 5.1 on 2024-08-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0004_alter_am_system_base_advantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='am_system',
            name='defender',
            field=models.CharField(choices=[('caldari', 'caldari'), ('gallente', 'gallente'), ('minmatar', 'minmatar'), ('amarr', 'amarr')], default='caldari', max_length=255),
        ),
        migrations.AddField(
            model_name='cg_system',
            name='defender',
            field=models.CharField(choices=[('caldari', 'caldari'), ('gallente', 'gallente'), ('minmatar', 'minmatar'), ('amarr', 'amarr')], default='caldari', max_length=255),
        ),
        migrations.AlterField(
            model_name='battlefieldcompletion',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='livebattlefield',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
