# Generated by Django 5.1 on 2024-08-23 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0004_alter_livebattlefield_fc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledbattlefield',
            old_name='is_between_noon_and_four_hours_after',
            new_name='is_between_downtime_and_four_hours_after',
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 19, 31, 12, 744759, tzinfo=datetime.timezone.utc)),
        ),
    ]
