# Generated by Django 5.1 on 2024-08-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0005_am_system_defender_cg_system_defender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlefieldcompletion',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livebattlefield',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
