# Generated by Django 5.1 on 2024-08-23 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0005_rename_is_between_noon_and_four_hours_after_scheduledbattlefield_is_between_downtime_and_four_hours_'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbattlefield',
            name='battlefield_type',
            field=models.CharField(choices=[('Downtime', 'Downtime'), ('Normal', 'Normal'), ('System Flipped', 'System Flipped')], default='Normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 20, 4, 43, 870773, tzinfo=datetime.timezone.utc)),
        ),
    ]
