# Generated by Django 5.1 on 2024-08-22 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0006_scheduledbattlefield_is_between_noon_and_four_hours_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldcompletion',
            name='converted_to_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 1, 34, 22, 153386, tzinfo=datetime.timezone.utc)),
        ),
    ]
