# Generated by Django 5.1 on 2024-08-22 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield_tracker', '0007_battlefieldcompletion_converted_to_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='expected_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 1, 34, 36, 537248, tzinfo=datetime.timezone.utc)),
        ),
    ]
