version: '3.8'

services:
  django:
    image: warzone_tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py setup_cron_jobs &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - ./warzone_tools:/warzone_tools
      - ./warzone_tools/static:/app/static
      - ./warzone_tools/staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
      - RQ_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  rqworker:
    image: warzone_tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py rqworker default
    volumes:
      - ./warzone_tools:/warzone_tools
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - frontend

  rqscheduler:
    image: warzone_tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py rqscheduler
    volumes:
      - ./warzone_tools:/warzone_tools
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./warzone_tools/staticfiles:/static
      - ./warzone_tools/media:/media
    depends_on:
      - django
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
