version: '3.8'

services:
  django:
    image: warzone_tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py setup_cron_jobs &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - ./warzone_tools:/warzone_tools
      - ./warzone_tools/static:/app/static
      - ./warzone_tools/staticfiles:/app/staticfiles
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DJANGO_DEBUG}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - EVE_CLIENT_ID=${EVE_CLIENT_ID}
      - EVE_SECRET_KEY=${EVE_SECRET_KEY}
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"] # This runs Redis with a default configuration and append-only mode.
    volumes:
      - ./redis-data:/data # Persist data to a directory on the host
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  rqworker:
    image: warzone_tools:latest
    container_name: rqworker
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py rqworker default
    volumes:
      - ./warzone_tools:/warzone_tools
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - backend
      - frontend

  rqscheduler:
    image: warzone_tools:latest
    container_name: rqscheduler
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py rqscheduler
    volumes:
      - ./warzone_tools:/warzone_tools
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./warzone_tools/static:/warzone_tools/static
      - ./warzone_tools/staticfiles:/warzone_tools/staticfiles
      - ./warzone_tools/media:/warzone_tools/media
    depends_on:
      - django
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge