services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./warzone_tools/staticfiles:/static
      - ./warzone_tools/media:/media
    depends_on:
      - django
    networks:
      - frontend
      - backend