# Generated by Django 5.1 on 2024-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionadvantage',
            name='dynamic_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factionadvantage',
            name='faction_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factionadvantage',
            name='terrain_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factionadvantage',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
