# Generated by Django 5.1 on 2024-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_tools', '0002_alter_factionadvantage_dynamic_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='contested_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='contested_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='occupier_faction',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='owner_faction',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
