# Generated by Django 5.1 on 2024-09-05 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_tools', '0004_alter_scheduledbattlefield_is_between_downtime_and_four_hours_after'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbattlefield',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='battlefields_as_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledbattlefield',
            name='fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battlefields_as_fc', to=settings.AUTH_USER_MODEL),
        ),
    ]
